config/routes.rb
Rails.application.routes.draw do
  resources :wishlists
  resources :orders
  # get 'idproofs/index'
  # get 'idproof/index'
  resources :categories
  # resources :productimages
  resources :idproofs 
  devise_for :merchants
  #  root to: "migrate#index"
  # get 'products/index'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root "products#index"
  resources :products do
    member do
      get :cart , to: 'carts#cart'
      get :wishlist, to: 'wishlists#create'
    end
  end
  
  resources :carts do
    member do
      get :order, to: "orders#create" 
      get :remove_from_carts, to: "carts#destroy"
    end
  end
  
  resources :wishlists do
   member do
    get :remove_from_wishlists, to: "wishlists#destroy"
   end 
  end

  resources :productimage
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
class Cart < ApplicationRecord
    # belongs_to :qty   
    belongs_to :merchant
    belongs_to :product
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :products
end

app/models/idproof.rb
class Idproof < ApplicationRecord
  belongs_to :merchant
  mount_uploader :document, ImageUploader
end

app/models/merchant.rb
class Merchant < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :product
  belongs_to :cart
  belongs_to :merchant
end

app/models/product.rb
class Product < ApplicationRecord
    validates :name, presence: true
    validates :description, presence: true, length: { minimum: 10 }
    validates :price, presence: true
    validates :category, presence: true
    validates  :status , presence: true
    belongs_to :category
    has_many :productimages
    has_many :cart

    enum :status, { "Pending": "Pending", "Accept": "Accept", "Reject": "Reject"},_default: :"Pending"
end     

app/models/productimage.rb
class Productimage < ApplicationRecord
    belongs_to :product
    mount_uploader :image, ImageUploader

end

app/models/wishlist.rb
class Wishlist < ApplicationRecord
  belongs_to :product
  belongs_to :merchant
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

 
    def index
     @carts = Cart.all
    end

    def show
      @cart = Cart.find(params[:id])
    end

    def new
     @cart = Cart.new
    end

    def cart
      @cart = Cart.new(product_id: params[:id], merchant_id: current_merchant.id, qty: 1)
      @cart.save!
      redirect_to products_path, notice: 'Added to Cart'
    end
     

    def destroy
     @cart = Cart.find(params[:id])
      @cart.destroy
    end
    
    private
  
      def carts_params
        params.require(:cart).permit(:qty,  :merchant_id, :product_id)
      end
  
  end
  

app/controllers/idproofs_controller.rb
class IdproofsController < ApplicationController
  def index 
    @idproofs = Idproof.all
  end

  def show
    @idproofs = Idproof.find(params[:id])
  end   
  def new
    @idproof = Idproof.new
  end

  def create
    @idproof = Idproof.new(idproof_params)
    @idproof.merchant_id = current_merchant.id

    if @idproof.save
      redirect_to @idproof
    else
      render :new, status: :unprocessable_entity
    end
  end

  
  def edit
    @idproof = Idproof.find(params[:id])
  end

  def update
    @idproof = Idproof.find(params[:id])

    if @idproof.update(idproof_params)
      redirect_to @idproof
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @idproof = Idproof.find(params[:id])
    @idproof.destroy
    
    redirect_to root_path, status: :see_other
  end

  
  
  private
   def set_idproof
    @idproofs = Idproof.find(params[:id])
   end

    def idproof_params
      params.require(:idproof).permit(:status, :document, :merchant_id)
    end
end

app/controllers/orders_controller.rb
class OrdersController < InheritedResources::Base

  def index
    @orders = Order.all
  end
  def show
    @order = Order.find(params[:id])
  end
  def create
    @order = Order.new(product_id: Cart.find(params[:id]).product.id, merchant_id: current_merchant.id, cart_id: params[:id], status: "Pending")
    @order.save!
    redirect_to orders_path, notice: "Order added succesfully...!"
  end
  def destroy
    @order = Order.find(params[:id])
    @order.destroy
    redirect_to orders_path, notice: "Order Cancelled"
  end


  
  private

    def order_params
      params.require(:order).permit(:status, :product_id, :cart_id, :merchant_id)
    end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    # @products = Product.all
    @products = Product.where(merchant_id: current_merchant.id)
  end
  
  def show
    @product = Product.find(params[:id])
  end   
  
  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    @product.merchant_id = current_merchant.id

    if @product.save
      redirect_to @product
    else
      render :new, status: :unprocessable_entity
    end
  end

  
  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])

    if @product.update(product_params)
      redirect_to @product
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    redirect_to root_path, status: :see_other
  end


  private
  def set_product
    @product = Product.find(params[:id])
  end
  def product_params
    params.require(:product).permit(:name, :description, :price, :category_id, :status, :merchant_id,)
  end
 

end

app/controllers/wishlists_controller.rb
class WishlistsController < ApplicationController
  def index
    @wishlists = Wishlist.all
  end
def show
  @wishlist = Wishlist.find(params[:id])
end
def new
  @wishlist = Wishlist.new
end
def create
  @wishlist = Wishlist.new(merchant_id: current_merchant.id, product_id: (params[:id]))
  if @wishlist.save
    redirect_to wishlists_path, notice: "Wishlist was successfully created."
  else
    render :new
  end
end
def edit
  @wishlist = Wishlist.find(params[:id])
end
def update
  @wishlist = Wishlist.find(params[:id])
  if @wishlist.update(wishlist_params)
    redirect_to wishlist_path(@wishlist), notice: "Wishlist was successfully updated."
  else
    render :edit
  end
end
def destroy
  @wishlist = Wishlist.find(params[:id])
  @wishlist.destroy
  redirect_to wishlists_path, notice: "Wishlist was successfully destroyed."
end
  private
    def wishlist_params
      params.require(:wishlist).permit(:product_id, :merchant_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/idproof_helper.rb
module IdproofHelper
end

app/helpers/idproofs_helper.rb
module IdproofsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/productimages_helper.rb
module ProductimagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/wishlists_helper.rb
module WishlistsHelper
end

app/views/orders/_form.html.erb
<%= form_with(model: order) do |form| %>
  <% if order.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
        <% order.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :status, style: "display: block" %>
    <%= form.text_field :status %>
  </div>

  <div>
    <%= form.label :product_id, style: "display: block" %>
    <%= form.text_field :product_id %>
  </div>

  <div>
    <%= form.label :cart_id, style: "display: block" %>
    <%= form.text_field :cart_id %>
  </div>

  <div>
    <%= form.label :merchant_id, style: "display: block" %>
    <%= form.text_field :merchant_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/orders/_order.html.erb
<div id="<%= dom_id order %>">
  <p>
    <strong>Status:</strong>
    <%= order.status %>
  </p>

  <p>
    <strong>Product:</strong>
    <%= order.product_id %>
  </p>

  <p>
    <strong>Cart:</strong>
    <%= order.cart_id %>
  </p>

  <p>
    <strong>Merchant:</strong>
    <%= order.merchant_id %>
  </p>

</div>

app/views/orders/edit.html.erb
<h1>Editing order</h1>

<%= render "form", order: @order %>

<br>

<div>
  <%= link_to "Show this order", @order %> |
  <%= link_to "Back to orders", orders_path %>
</div>

app/views/orders/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Orders</h1>

<div id="orders">
  <% @orders.each do |order| %>
    <%= render order %>
    <p>
      <%= link_to "Show this order", order %>
    </p>
  <% end %>
</div>

<%= link_to "New order", new_order_path %>

app/views/orders/new.html.erb
<h1>New order</h1>

<%= render "form", order: @order %>

<br>

<div>
  <%= link_to "Back to orders", orders_path %>
</div>

app/views/orders/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @order %>

<div>
  <%= link_to "Edit this order", edit_order_path(@order) %> |
  <%= link_to "Back to orders", orders_path %>

  <%= button_to "Destroy this order", @order, method: :delete %>
</div>

app/views/products/_code.html.erb

<%# ----------------style------------------- %>

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
<div class="conteiner">
  <h3 class="h3">BUISNESS</h3>
    <div class="row float-left ">
       <% Product.all.each do |product| %>
        <div class="col-md-3 col-sm-6">
          <div class="product-grid">
            <div class="product-image">
              <a>
                <img class="pic-1 " src="<%=product.productimages.first.image  if product.productimages.any?%>">
                <%# <img class="pic-2" src="https://www.w3schools.com/bootstrap4/img_avatar3.png"> %>
              </a>
              <ul class="social">
                <li><a href="" data-tip="Quick View"><i class="fa fa-search"></i></a></li>
                <li><a href="" data-tip="Add to Wishlist"><i class="fa fa-shopping-bag"></i></a></li>
                <li><a href="" data-tip="Add to Cart"><i class="fa fa-shopping-cart"></i></a></li>
              </ul>
              <span class="product-new-label">Sale</span>
              <%# <span class="product-discount-label">20%</span> %>
            </div>
             
            <div class="product-content">
              <h3 class="title">
                <h6><a href="products/<%=product.id%>"><%=product.name%></a></h6>
                <div class="price">₹<%= product.price %><br>
                </a></h3>
              <h6>Status:<%= product.status %></h6> 
              <h6><b>Category:</b><%= Category.find(product.category_id).categoryname %></h6>
            </div>
            <a><%= product.description %></a><br>
                    <%# <a class="add-to-cart" href="cartscvirendra=2">+ Add To Cart</a> %>
                    <a class="add-to-cart" href="<%=cart_product_path(product.id)%>">+Add To Cart</a>


          </div>
        </div>
        <%# <p class="link_para "><%= link_to "Show this product", product %></p> 
      </div>  
  
  
     <% end %>
    </div>
</div>

app/views/products/_form.html.erb
<%= form_for  @product do |form| %>
 <div>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %><br>
  </div>
 
  <div>
    <%= form.label :price %><br>
    <%= form.number_field :price %><br>
  </div>

  <div>
    <%= form.label :category %><br>
    <%= form.collection_select  :category_id, Category.all, :id, :categoryname %><br>
  </div>
   
   
  <div>
    <%= form.label :status %><br>
    <%= form.select :status, Product.statuses.keys %><br>     
  </div>
 </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>




app/views/products/edit.html.erb
<h1>Edit product</h1>
<%= render "form", product: @product %>

app/views/products/index.html.erb
<HTML>
<head>
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!------ Include the above in your HEAD tag ---------->
​
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
​</head>


<body>
<h1>Products</h1>
<%# @products.each do |pro| %>
    <%= render 'code' %>
<%# end %>
</body>
</HTML>











<%# productindex
<h1>Products</h1>

<%= link_to "New Product", new_product_path %>
<%#= link_to "New Product Image", new_productimage_path %>
<%#= link_to "New ID proof",  new_idproof_path%>


<%# <ul> %>
  <%# <% @products.each do |product| %>
    <%# <li> %>
  <%# <strong>name: </strong> %>
  <%#= product.name %>

  <%# <strong>description:</strong> %>
  <%# <%= product.description %>

  <%# <strong>price: </strong> %>
  <%#= product.price %>

  <%# <strong>category: </strong> %>
  <%#= Category.find(product.category_id).categoryname %>

  <%# <strong>status:  </strong> %>
  <%#= product.status %>

  <%#= link_to "show", product   %>

    <%# </li> %>
  <%# end %>
<%# </ul> %>

<%#= link_to "New Product", new_product_path %>



​

app/views/products/new.html.erb
<h1>product</h1>

<%= render "form", product: @product %>

app/views/products/show.html.erb

  <strong>name: </strong>
  <%= @product.name %><br>

  <strong>description</strong>
  <%= @product.description %><br>

   <strong>price </strong>
  <%= @product.price %><br>

    <strong>category </strong>
    <%= Category.find(@product.category_id).categoryname %><br>

    <strong>status </strong>  
    <%= @product.status %><br>
   
   <%= render @product.productimages %>
   <%= render "productimages/form" %>


  <ul>
  <li><%= link_to "Edit", edit_product_path(@product) %></li>
  <li><%= link_to "Destroy", product_path(@product), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %></li>
  </ul>

app/views/wishlists/_form.html.erb
<%= form_with(model: wishlist) do |form| %>
  <% if wishlist.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(wishlist.errors.count, "error") %> prohibited this wishlist from being saved:</h2>

      <ul>
        <% wishlist.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :order, style: "display: block" %>
    <%= form.text_field :order %>
  </div>

  <div>
    <%= form.label :product_id, style: "display: block" %>
    <%= form.text_field :product_id %>
  </div>

  <div>
    <%= form.label :merchant_id, style: "display: block" %>
    <%= form.text_field :merchant_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/wishlists/_wishlist.html.erb
<div id="<%= dom_id wishlist %>">
  <p>
    <strong>Order:</strong>
    <%= wishlist.order %>
  </p>

  <p>
    <strong>Product:</strong>
    <%= wishlist.product_id %>
  </p>

  <p>
    <strong>Merchant:</strong>
    <%= wishlist.merchant_id %>
  </p>

</div>

app/views/wishlists/edit.html.erb
<h1>Editing wishlist</h1>

<%= render "form", wishlist: @wishlist %>

<br>

<div>
  <%= link_to "Show this wishlist", @wishlist %> |
  <%= link_to "Back to wishlists", wishlists_path %>
</div>

app/views/wishlists/index.html.erb
<%# <p style="color: green"><%= notice %></p> %>

<%# <h1>Wishlists</h1>

<div id="wishlists"> %>
  <%# @wishlists.each do |wishlist| %>
    <%#= render wishlist %>
    <%# <p> %>
      <%#= link_to "Show this wishlist", wishlist %>
    <%# </p> %>
  <%# end %>
<%# </div> %>
<%#  %>
<%#= link_to "New wishlist", new_wishlist_path %>



<link
  href="https://netdna.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css"
  rel="stylesheet"
  id="bootstrap-css"
/>
<script src="https://netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
<script src="https://code.jquery.com/jquery-1.11.1.min.js"></script>



<body>
  <div class="container wrapper">
    <div class="row wishlist-body">
      <form class="form-horizontal" method="post" action="">
        <div
          class=""
        >
          <!--REVIEW ORDER-->
          <div class="panel panel-info">
            <div class="panel-heading">
              Review Order
            </div>
            <div class="panel-body">
              <div class="form-group">

                <% @wishlists.each do |wishlist| %>
                <div class="col-sm-3 col-xs-3">
                  <img
                    class="img-responsive"
                    src="<%=wishlist.product.productimages.first.image  if wishlist.product.productimages.any?%>"width="100px" height="70px"
                  />
                </div>
          
                <div class="col-sm-6 col-xs-6">
                  <div class="col-xs-12"><%= wishlist.product.name %></div>
                  <a href="" >
                  <div class="col-xs-12">
                    <small>Quantity:<span>1</span></small>
                  </div>
                </div>
                <div class="col-sm-3 col-xs-3 text-right">
                  <h6><span>$</span><%= wishlist.product.price %></h6>
                </div>
                <div>
                  <%= link_to "Destroy this wishlist|", "/wishlists/#{wishlist.id }/remove_from_wishlists" %>
                 </div>
              
              <%# </div> %>
              <div class="form-group"><hr /></div>             
                <% end %>
                <div class="col-xs-12">
                  <small>Shipping</small>
                  <div class="pull-right"><span>-</span></div>
                </div>
              <%# </div> %>
              <div class="form-group"><hr /></div>
              <div class="form-group">
                <div class="col-xs-12">
                  <strong>Order Total</strong>
                  <div class="pull-right"><span>$</span><span>150.00</span></div>
                </div>
              </div>
                <div class="form-group">
                  <div class="col-xs-12">
                    <div class="pull-right"><span></span><span><a class="btn-primary btn" href="">Checkout</a></span></div>
                  </div>
                </div>
            </div>
          </div>
        </div>
      </form>
    </div>
  </div>
  
</body>

app/views/wishlists/new.html.erb
<h1>New wishlist</h1>

<%= render "form", wishlist: @wishlist %>

<br>

<div>
  <%= link_to "Back to wishlists", wishlists_path %>
</div>

app/views/wishlists/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @wishlist %>

<div>
  <%= link_to "Edit this wishlist", edit_wishlist_path(@wishlist) %> |
  <%= link_to "Back to wishlists", wishlists_path %>

  <%= button_to "Destroy this wishlist", @wishlist, method: :delete %>
</div>