config/routes.rb
Rails.application.routes.draw do
  resources :wishlists
  resources :orders
  # get 'idproofs/index'
  # get 'idproof/index'
  resources :categories
  # resources :productimages
  resources :idproofs 
  devise_for :merchants
  #  root to: "migrate#index"
  # get 'products/index'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root "products#index"
  resources :products do
    member do
      get :cart , to: 'carts#cart'
      get :wishlist, to: 'wishlists#create'
    end
  end
  
  resources :carts do
    member do
      get :order, to: "orders#create" 
      get :remove_from_carts, to: "carts#destroy"
    end
  end
  
  resources :wishlists do
   member do
    get :remove_from_wishlists, to: "wishlists#destroy"
   end 
  end

  resources :productimage
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
class Cart < ApplicationRecord
    # belongs_to :qty   
    belongs_to :merchant
    belongs_to :product
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :products
end

app/models/idproof.rb
class Idproof < ApplicationRecord
  belongs_to :merchant
  mount_uploader :document, ImageUploader
end

app/models/merchant.rb
class Merchant < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :product
  belongs_to :cart
  belongs_to :merchant
end

app/models/product.rb
class Product < ApplicationRecord
    validates :name, presence: true
    validates :description, presence: true, length: { minimum: 10 }
    validates :price, presence: true
    validates :category, presence: true
    validates  :status , presence: true
    belongs_to :category
    has_many :productimages
    has_many :cart

    enum :status, { "Pending": "Pending", "Accept": "Accept", "Reject": "Reject"},_default: :"Pending"
end     

app/models/productimage.rb
class Productimage < ApplicationRecord
    belongs_to :product
    mount_uploader :image, ImageUploader

end

app/models/wishlist.rb
class Wishlist < ApplicationRecord
  belongs_to :product
  belongs_to :merchant
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

 
    def index
     @carts = Cart.all
    end

    def show
      @cart = Cart.find(params[:id])
    end

    def new
     @cart = Cart.new
    end

    def cart
      @cart = Cart.new(product_id: params[:id], merchant_id: current_merchant.id, qty: 1)
      @cart.save!
      redirect_to products_path, notice: 'Added to Cart'
    end
     

    def destroy
     @cart = Cart.find(params[:id])
      @cart.destroy
    end
    
    private
  
      def carts_params
        params.require(:cart).permit(:qty,  :merchant_id, :product_id)
      end
  
  end
  

app/controllers/idproofs_controller.rb
class IdproofsController < ApplicationController
  def index 
    @idproofs = Idproof.all
  end

  def show
    @idproofs = Idproof.find(params[:id])
  end   
  def new
    @idproof = Idproof.new
  end

  def create
    @idproof = Idproof.new(idproof_params)
    @idproof.merchant_id = current_merchant.id

    if @idproof.save
      redirect_to @idproof
    else
      render :new, status: :unprocessable_entity
    end
  end

  
  def edit
    @idproof = Idproof.find(params[:id])
  end

  def update
    @idproof = Idproof.find(params[:id])

    if @idproof.update(idproof_params)
      redirect_to @idproof
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @idproof = Idproof.find(params[:id])
    @idproof.destroy
    
    redirect_to root_path, status: :see_other
  end

  
  
  private
   def set_idproof
    @idproofs = Idproof.find(params[:id])
   end

    def idproof_params
      params.require(:idproof).permit(:status, :document, :merchant_id)
    end
end

app/controllers/orders_controller.rb
class OrdersController < InheritedResources::Base

  def index
    @orders = Order.all
  end
  def show
    @order = Order.find(params[:id])
  end
  def create
    @order = Order.new(product_id: Cart.find(params[:id]).product.id, merchant_id: current_merchant.id, cart_id: params[:id], status: "Pending")
    @order.save!
    redirect_to orders_path, notice: "Order added succesfully...!"
  end
  def destroy
    @order = Order.find(params[:id])
    @order.destroy
    redirect_to orders_path, notice: "Order Cancelled"
  end


  
  private

    def order_params
      params.require(:order).permit(:status, :product_id, :cart_id, :merchant_id)
    end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    # @products = Product.all
    @products = Product.where(merchant_id: current_merchant.id)
  end
  
  def show
    @product = Product.find(params[:id])
  end   
  
  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    @product.merchant_id = current_merchant.id

    if @product.save
      redirect_to @product
    else
      render :new, status: :unprocessable_entity
    end
  end

  
  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])

    if @product.update(product_params)
      redirect_to @product
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    redirect_to root_path, status: :see_other
  end


  private
  def set_product
    @product = Product.find(params[:id])
  end
  def product_params
    params.require(:product).permit(:name, :description, :price, :category_id, :status, :merchant_id,)
  end
 

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/idproof_helper.rb
module IdproofHelper
end

app/helpers/idproofs_helper.rb
module IdproofsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/productimages_helper.rb
module ProductimagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/wishlists_helper.rb
module WishlistsHelper
end

app/views/carts/_cartcode.html.erb
<link
  href="https://netdna.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css"
  rel="stylesheet"
  id="bootstrap-css"
/>
<script src="https://netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
<script src="https://code.jquery.com/jquery-1.11.1.min.js"></script>



<body>
  <div class="container wrapper">
    <div class="row cart-body">
      <form class="form-horizontal" method="post" action="">
        <div
          class=""
        >
          <!--REVIEW ORDER-->
          <div class="panel panel-info">
            <div class="panel-heading">
              Review Order
            </div>
            <div class="panel-body">
              <div class="form-group">

                <% @carts.each do |cart| %>
                <div class="col-sm-3 col-xs-3">
                  <img
                    class="img-responsive"
                    src="<%=cart.product.productimages.first.image  if cart.product.productimages.any?%>"width="100px" height="70px"
                  />
                </div>
          
                <div class="col-sm-6 col-xs-6">
                  <div class="col-xs-12"><%= cart.product.name %></div>
                  <a href="" >
                  <div class="col-xs-12">
                    <small>Quantity:<span>1</span></small>
                  </div>
                </div>
                <div class="col-sm-3 col-xs-3 text-right">
                  <h6><span>$</span><%= cart.product.price %></h6>
                </div>
                <div>
                 <%= link_to "Order|  ", order_cart_path(cart) %>
                  <%= link_to "wishlist|", wishlist_product_path(cart)  %> 
                  <%= link_to "Destroy this cart|", "/carts/#{cart.id }/remove_from_carts" %>
                 </div>
              
              <%# </div> %>
              <div class="form-group"><hr /></div>             
                <% end %>
                <div class="col-xs-12">
                  <small>Shipping</small>
                  <div class="pull-right"><span>-</span></div>
                </div>
              <%# </div> %>
              <div class="form-group"><hr /></div>
              <div class="form-group">
                <div class="col-xs-12">
                  <strong>Order Total</strong>
                  <div class="pull-right"><span>$</span><span>150.00</span></div>
                </div>
              </div>
                <div class="form-group">
                  <div class="col-xs-12">
                    <div class="pull-right"><span></span><span><a class="btn-primary btn" href="">Checkout</a></span></div>
                  </div>
                </div>
            </div>
          </div>
        </div>
      </form>
    </div>
  </div>
  
</body>

app/views/carts/_style.html.erb
<style>
  html,
  body,


  .wrapper {
    background: #f7f7f7;
     padding-top: 50px;
  }
  .steps {
    margin-top: -41px;
    display: inline-block;
    float: right;
    font-size: 16px;
  }
  .step {
    float: left;
    background: white;
    padding: 7px 13px;
    border-radius: 1px;
    text-align: center;
    width: 100px;
    position: relative;
  }
  .step_line {
    margin: 0;
    width: 0;
    height: 0;
    border-left: 16px solid #fff;
    border-top: 16px solid transparent;
    border-bottom: 16px solid transparent;
    z-index: 1008;
    position: absolute;
    left: 99px;
    top: 1px;
  }
  .step_line.backline {
    border-left: 20px solid #f7f7f7;
    border-top: 20px solid transparent;
    border-bottom: 20px solid transparent;
    z-index: 1006;
    position: absolute;
    left: 99px;
    top: -3px;
  }
  .step_complete {
    background: #357ebd;
  }
  .step_complete a.check-bc,
  .step_complete a.check-bc:hover,
  .afix-1,
  .afix-1:hover {
    color: #eee;
  }
  .step_line.step_complete {
    background: 0;
    border-left: 16px solid #357ebd;
  }
  .step_thankyou {
    float: left;
    background: white;
    padding: 7px 13px;
    border-radius: 1px;
    text-align: center;
    width: 100px;
  }
  .step.check_step {
    margin-left: 5px;
  }
  .ch_pp {
    text-decoration: underline;
  }
  .ch_pp.sip {
    margin-left: 10px;
  }
  .check-bc,
  .check-bc:hover {
    color: #222;
  }
  .SuccessField {
    border-color: #458845 !important;
    -webkit-box-shadow: 0 0 7px #9acc9a !important;
    -moz-box-shadow: 0 0 7px #9acc9a !important;
    box-shadow: 0 0 7px #9acc9a !important;
    background: #f9f9f9 url(../images/valid.png) no-repeat 98% center !important;
  }
​
  .btn-xs {
    line-height: 28px;
  }
​
  /*login form*/
  .login-container {
    margin-top: 30px;
  }
  .login-container input[type="submit"] {
    width: 100%;
    display: block;
    margin-bottom: 10px;
    position: relative;
  }
​
  .login-container input[type="text"],
  input[type="password"] {
    height: 44px;
    font-size: 16px;
    width: 100%;
    margin-bottom: 10px;
    -webkit-appearance: none;
    background: #fff;
    border: 1px solid #d9d9d9;
    border-top: 1px solid #c0c0c0;
    /* border-radius: 2px; */
    padding: 0 8px;
    box-sizing: border-box;
    -moz-box-sizing: border-box;
  }
​
  .login-container input[type="text"]:hover,
  input[type="password"]:hover {
    border: 1px solid #b9b9b9;
    border-top: 1px solid #a0a0a0;
    -moz-box-shadow: inset 0 1px 2px rgba(0, 0, 0, 0.1);
    -webkit-box-shadow: inset 0 1px 2px rgba(0, 0, 0, 0.1);
    box-shadow: inset 0 1px 2px rgba(0, 0, 0, 0.1);
  }
​
  .login-container-submit {
    /* border: 1px solid #3079ed; */
    border: 0px;
    color: #fff;
    text-shadow: 0 1px rgba(0, 0, 0, 0.1);
    background-color: #357ebd; /*#4d90fe;*/
    padding: 17px 0px;
    font-family: roboto;
    font-size: 14px;
    /* background-image: -webkit-gradient(linear, 0 0, 0 100%,   from(#4d90fe), to(#4787ed)); */
  }
​
  .login-container-submit:hover {
    /* border: 1px solid #2f5bb7; */
    border: 0px;
    text-shadow: 0 1px rgba(0, 0, 0, 0.3);
    background-color: #357ae8;
    /* background-image: -webkit-gradient(linear, 0 0, 0 100%,   from(#4d90fe), to(#357ae8)); */
  }
​
  .login-help {
    font-size: 12px;
  }
​
  .asterix {
    background: #f9f9f9 url(../images/red_asterisk.png) no-repeat 98% center !important;
  }
​
  /* images*/
  ol,
  ul {
    list-style: none;
  }
  .hand {
    cursor: pointer;
    cursor: pointer;
  }
  .cards {
    padding-left: 0;
  }
  .cards li {
    -webkit-transition: all 0.2s;
    -moz-transition: all 0.2s;
    -ms-transition: all 0.2s;
    -o-transition: all 0.2s;
    transition: all 0.2s;
    background-image: url("//c2.staticflickr.com/4/3713/20116660060_f1e51a5248_m.jpg");
    background-position: 0 0;
    float: left;
    height: 32px;
    margin-right: 8px;
    text-indent: -9999px;
    width: 51px;
  }
  .cards .mastercard {
    background-position: -51px 0;
  }
  .cards li {
    -webkit-transition: all 0.2s;
    -moz-transition: all 0.2s;
    -ms-transition: all 0.2s;
    -o-transition: all 0.2s;
    transition: all 0.2s;
    background-image: url("//c2.staticflickr.com/4/3713/20116660060_f1e51a5248_m.jpg");
    background-position: 0 0;
    float: left;
    height: 32px;
    margin-right: 8px;
    text-indent: -9999px;
    width: 51px;
  }
  .cards .amex {
    background-position: -102px 0;
  }
  .cards li {
    -webkit-transition: all 0.2s;
    -moz-transition: all 0.2s;
    -ms-transition: all 0.2s;
    -o-transition: all 0.2s;
    transition: all 0.2s;
    background-image: url("//c2.staticflickr.com/4/3713/20116660060_f1e51a5248_m.jpg");
    background-position: 0 0;
    float: left;
    height: 32px;
    margin-right: 8px;
    text-indent: -9999px;
    width: 51px;
  }
  .cards li:last-child {
    margin-right: 0;
  }
  /* images end */
​
  /*
 * BOOTSTRAP
 */
  .container {
    border: none;
  }
  .panel-footer {
    background: #fff;
  }
  .btn {
    border-radius: 1px;
  }
  .btn-sm,
  .btn-group-sm > .btn {
    border-radius: 1px;
  }
  .input-sm,
  .form-horizontal .form-group-sm .form-control {
    border-radius: 1px;
  }
​
  .panel-info {
    border-color: #999;
  }
​
  .panel-heading {
    border-top-left-radius: 1px;
    border-top-right-radius: 1px;
  }
  .panel {
    border-radius: 1px;
  }
  .panel-info > .panel-heading {
    color: #eee;
    border-color: #999;
  }
  .panel-info > .panel-heading {
    background-image: linear-gradient(to bottom, #555 0px, #888 100%);
  }
​
  hr {
    border-color: #999 -moz-use-text-color -moz-use-text-color;
  }
​
  .panel-footer {
    border-bottom-left-radius: 1px;
    border-bottom-right-radius: 1px;
    border-top: 1px solid #999;
  }
​
  .btn-link {
    color: #888;
  }
​
  hr {
    margin-bottom: 10px;
    margin-top: 10px;
  }
​
  /** MEDIA QUERIES **/
  @media only screen and (max-width: 989px) {
    .span1 {
      margin-bottom: 15px;
      clear: both;
    }
  }
​
  @media only screen and (max-width: 764px) {
    .inverse-1 {
      float: right;
    }
  }
​
  @media only screen and (max-width: 586px) {
    .cart-titles {
      display: none;
    }
    .panel {
      margin-bottom: 1px;
    }
  }
​
  .form-control {
    border-radius: 1px;
  }
​
  @media only screen and (max-width: 486px) {
    .col-xss-12 {
      width: 100%;
    }
    .cart-img-show {
      display: none;
    }
    .btn-submit-fix {
      width: 100%;
    }
  }
  /*
@media only screen and (max-width: 777px){
    .container{
        overflow-x: hidden;
    }
}*/
</style>

app/views/carts/index.html.erb
<%=render 'cartcode'%>
<%=render 'style'%>

app/views/carts/show.html.erb
 <%# <strong>qty: </strong>
  <%= @cart.qty %>
<%# 
  <strong>merchant_id</strong>
  <%= @cart.merchant_id %>

   <%# <strong>product_id </strong>
  <%= @cart.product_id %>

<%=render 'cartcode'%>


app/views/categories/_category.html.erb
<div id="<%= dom_id category %>">
  <p>
    <strong>Categoryname:</strong>
    <%= category.categoryname %>
  </p>

</div>

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <% if category.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :categoryname, style: "display: block" %>
    <%= form.text_field :categoryname %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Show this category", @category %> |
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Categories</h1>

<div id="categories">
  <% @categories.each do |category| %>
    <%= render category %>
    <p>
      <%= link_to "Show this category", category %>
    </p>
  <% end %>
</div>

<%= link_to "New category", new_category_path %>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @category %>

<div>
  <%= link_to "Edit this category", edit_category_path(@category) %> |
  <%= link_to "Back to categories", categories_path %>

  <%= button_to "Destroy this category", @category, method: :delete %>
</div>